[package]
name = "moody"
version = "0.1.0"
authors = ["Maneesh Babu M <maneeshbabum@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
